### ISSUE TITLE
EWA in pandas

### ISSUE THREAD

**Issue by rth** [alexisrosuel/PyEWA#12]
Just a random question @alexisrosuel , are you aware of EWA capabilities in pandas https://pandas.pydata.org/pandas-docs/stable/computation.html#exponentially-weighted-windows ? 

Or is this package doing something different? Generally the rolling windows calculation in pandas (`.rolling` attributes) are quite efficient (and probably written in Cython / C)..

**Comment by alexisrosuel** [comment]
Hi @rth  ! Thanks for coming here :) 

In fact it's some totally different topic : Aggregation by exponential weighting is a recent field of research in statistics. It's closely related to online learning algorithms, which can also be used for batch learning.

Some recent french researchers (which also have been my teacher this year) are currently proving the validity of these algorithms. As I saw that it doesn't seems to be implemented in Python yet, I decided to propose a base.

(any improvement about the code itself or anything is welcome as I am a beginner in producing professionnal code, with docs, ci, tests, etc. ;) )

If you want more details you can see this papers (it's some relatively advanced subjects) :
http://www.crest.fr/ckfinder/userfiles/files/pageperso/tsybakov/DTcolt2007.pdf
http://imagine.enpc.fr/publications/papers/ML08a.pdf

**Comment by rth** [comment]
Aww, interesting project. 

Well, if you are looking for some feedback (I know it's a new project),
  - if might help to have some explanations in the Readme what "Aggregation by exponential weighting " is used for in practice 
   - If you want to be compatible with the scikit-learn API, you might be interested in http://scikit-learn.org/stable/developers/contributing.html#rolling-your-own-estimator and http://scikit-learn.org/stable/developers/contributing.html#coding-guidelines

> (any improvement about the code itself or anything is welcome as I am a beginner in producing professionnal code, with docs, ci, tests, etc. ;) )

Also, if you have a chance, https://indico.lal.in2p3.fr/event/3504/ should address those points. Registrations are now officially closed, but one never knows ..

**Comment by alexisrosuel** [comment]
Thanks a lot :)
